### PR TITLE
Improved some of the documentation

### PR DESCRIPTION
**Pull request by imcodingideas**
I added a Contributors section, as well as borrowed the license from the FreeCodeCamp repo, and added it.

### CODE REVIEW

**Comment by imcodingideas** [comment]
There si a issue with the CI build as it's failing because: 

`Uncaught MongoError: failed to connect to server [undefined:27017] on first connect [MongoError: getaddrinfo ENOTFOUND undefined undefined:27017`

However; that's an issue with the database. Right?

**Comment by user512** [comment]
👍 Looks great to me

**Comment by imcodingideas** [comment]
Thanks! What do you think about my other PR https://github.com/freeCodeCamp/classroom-mode/pull/62 hehe

**Comment by user512** [comment]
#62 is even better and I answered one of your blocker in that PR here: https://github.com/freeCodeCamp/classroom-mode/pull/62#issuecomment-382615797

**Pull request merged**
