### PR TITLE
Feature: Teacher can edit students

### LINKED ISSUE #59: Teacher can edit students
Refer https://projects.invisionapp.com/share/J3C03W2SX#/screens/237080322

Nice to have: Modal to edit students?

### PR DESCRIPTION
**Pull request by AryanJ-NYC**
# Changes
* Add `EditStudent.js` modal
* Add `Edit` button in StudentRow Actions column
* Add `/students` PUT route
* Update to React 16.3.2
  * This was necessary to take advantage of `getDerivedStateFromProps` lifecycle method
* Moved `ClassTable.js` and `ClassTable.css` to their own folder

# Next Steps
The two modals (`AddStudentForm` and `EditStudent`) are nearly identical. They should be merged as to keep code DRY.

Closes #59.

### CODE REVIEW

**Comment by imcodingideas** [comment]
Thanks for your help! You sir, are awesome. I will test it, and if all is fine I will merge it.

**Comment by user512** [comment]
@utsab can you enforce CI must pass on Github before merging? We should also make sure new feature has enough test coverage.

**Comment by utsab** [comment]
@user512 yes I'll focus on this during tomorrow's hour of code.

**Comment by imcodingideas** [comment]
@user512 and @utsab this failed due to a connection error.

**Comment by AryanJ-NYC** [comment]
Thanks @user512, what should I do about the failed connection? That seems to be like an error in the CI.

**Comment by user512** [comment]
@AryanJ-NYC #91 should fix the failed connection problem for you, do you mind rebasing your branch?

**Comment by user512** [comment]
@AryanJ-NYC The frontend test should be back to a normal state if you remove `jest` in 
7bba53f.
`react-script` already take care of that.

**Comment by user512** [comment]
@AryanJ-NYC Thanks for adding the client test, I am more than happy to add the backend test since you have already made a great amount of progress, let me know 😄

**Comment by AryanJ-NYC** [comment]
Hey @user512. I wouldn't want to block development. If you have time, yes, please write the backend tests. If not, I have time to do it tomorrow night. :)

**Pull request merged**
